server:
  port: ${port:2222}

spring:
  application:
    name: first-service
  profiles:
    active: production

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
#    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: DEBUG
#  file: app.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8888

# CUSTOM PROPERTIES
my:
  servers:
    - dev.bar.com
    - foo.bar.com

---

spring:
  profiles: production
  application:
    name: first-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test-database
      username: root
      password: example
      authentication-database: admin